apiVersion: apps/v1
kind: Deployment
metadata:
  name: aisdeployment
  labels:
    app: audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
      - name: audit-service
        image: <your_audit_service_image>
        ports:
        - containerPort: 5000
